name: Tạo dự án Unity Ngọc Rồng

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy mỗi ngày lúc 00:00 UTC
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cronjob-based-github-action:
    name: Cronjob based github action (keep workflow alive)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2

  main:
    name: Tải và tạo dự án Unity
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Tải xuống phiên bản Ngọc Rồng Online và giải nén
        run: |
          $link = "http://dl.teamobi.com/drive/get/index.php?id=wd"
          Invoke-WebRequest -UseBasicParsing -Uri $link -Method "POST" -ContentType "application/x-www-form-urlencoded" -Body "submit=1" -OutFile "DragonBoyOnline.rar"
          & 'C:\Program Files\7-Zip\7z.exe' x DragonBoyOnline.rar -oDragonBoyOnline

      - name: Tải AssemblyCSharpPreprocessor
        uses: dawidd6/action-download-artifact@v6
        with:
          name: AssemblyCSharpPreprocessor
          repo: ElectroHeavenVN/Dragonboy-CommunityMod-Builds
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-asmpre.yml
          workflow_conclusion: success
          allow_forks: false
          skip_unpack: true

      - name: Giải nén AssemblyCSharpPreprocessor
        run: Expand-Archive -Path AssemblyCSharpPreprocessor.zip -DestinationPath AssemblyCSharpPreprocessor

      - name: Chạy AssemblyCSharpPreprocessor
        run: |
          $assemblyCSharp = Get-ChildItem -Path DragonBoyOnline -Filter Assembly-CSharp.dll -Recurse -ErrorAction SilentlyContinue -Force
          AssemblyCSharpPreprocessor/AssemblyCSharpPreprocessor.exe $assemblyCSharp.FullName -d -r -o
          Remove-Item -Force "$($assemblyCSharp.Directory.FullName)\Assembly-CSharp-original.dll"

      - name: Tải xuống AssetRipper.CLI
        uses: dawidd6/action-download-artifact@v6
        with:
          name: AssetRipper.CLI
          repo: ElectroHeavenVN/AssetRipper
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: publish-cli.yml
          workflow_conclusion: success
          branch: master
          allow_forks: false
          skip_unpack: true

      - name: Giải nén AssetRipper.CLI
        run: Expand-Archive -Path AssetRipper.CLI.zip -DestinationPath AssetRipper.CLI

      - name: Tạo dự án Unity
        run: |
          AssetRipper.CLI/AssetRipper.CLI.exe DragonBoyOnline DBO-UnityProject

      - name: Cài đặt ilspycmd
        run: |
          dotnet tool install ilspycmd -g

      - name: Dịch ngược Assembly-CSharp.dll
        run: |
          $assemblyCSharpPath = (Get-ChildItem -Path DragonBoyOnline -Filter Assembly-CSharp.dll -Recurse -ErrorAction SilentlyContinue -Force).FullName
          ilspycmd -p -lv CSharp7_3 --nested-directories -o decompiled-code $assemblyCSharpPath

      - name: Di chuyển mã nguồn đã dịch ngược
        run: |
          Remove-Item -Recurse -Force decompiled-code\Assembly-CSharp.csproj
          foreach ($file in Get-ChildItem -Path decompiled-code\* -Recurse -File) {
            Write-Host "Moving $($file.FullName) to DBO-UnityProject\ExportedProject\Assets\Scripts\Assembly-CSharp\$($file.FullName.Substring($file.FullName.IndexOf('decompiled-code\') + 16))"
            Move-Item $file.FullName -Destination "DBO-UnityProject\ExportedProject\Assets\Scripts\Assembly-CSharp\$($file.FullName.Substring($file.FullName.IndexOf('decompiled-code\') + 16))" -Force
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DBO-UnityProject
          path: DBO-UnityProject\ExportedProject

      - name: Nén dự án Unity
        run: Compress-Archive -Path DBO-UnityProject\ExportedProject -DestinationPath DBO-UnityProject.zip

      - name: Phát hành artifact
        uses: softprops/action-gh-release@v2
        with:
          files: DBO-UnityProject.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: DBO-UnityProject
          draft: false
          prerelease: false
          tag_name: "latest"
